//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Annarverkefni.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Card()
        {
            this.PlayersDecks = new HashSet<PlayersDeck>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Hp { get; set; }
        public int Dps { get; set; }
        public int Mana { get; set; }
        public string Info { get; set; }
        public bool Active { get; set; }
        public int CardType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayersDeck> PlayersDecks { get; set; }
    }
}
